openapi: 3.0.0
info:
  title: Task Manager API
  description: API task manager.
  version: 1.0.0
servers:
  - url: http://localhost:3000/api
    description: Servidor Local (Docker)

paths:
  /projects:
    get:
      tags:
        - Projetos
      summary: Listar todos os meus projetos
      responses:
        '200':
          description: Lista de projetos devolvida com sucesso.
    post:
      tags:
        - Projetos
      summary: Criar um projeto novo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectInput'
      responses:
        '201':
          description: Projeto criado.

  /projects/{id}:
    put:
      tags:
        - Projetos
      summary: Atualizar um projeto existente
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/ProjectInput'
      responses:
        '200':
          description: Projeto atualizado.
    delete:
      tags:
        - Projetos
      summary: Eliminar um projeto
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Projeto apagado.

  /tasks:
    get:
      tags:
        - Tarefas
      summary: Listar todas as tarefas
      responses:
        '200':
          description: Sucesso.
    post:
      tags:
        - Tarefas
      summary: Criar uma tarefa nova
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskInput'
      responses:
        '201':
          description: Tarefa criada.

  /tasks/{id}:
    put:
      tags:
        - Tarefas
      summary: Atualizar uma tarefa
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/TaskUpdate'
      responses:
        '200':
          description: Tarefa atualizada.
    delete:
      tags:
        - Tarefas
      summary: Eliminar uma tarefa
      parameters:
        - in: path
          name: id
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: Tarefa apagada.

  /users:
    get:
      tags:
        - Utilizadores
      summary: Listar utilizadores do sistema
      responses:
        '200':
          description: Sucesso.

components:
  schemas:
    ProjectInput:
      type: object
      required:
        - title
      properties:
        title:
          type: string
          example: "Novo Projeto"
        description:
          type: string
          example: "Descrição detalhada do projeto"
    
    TaskInput:
      type: object
      required:
        - title
        - ProjectId
      properties:
        title:
          type: string
          example: "Minha primeira tarefa"
        status:
          type: string
          example: "pendente"
        ProjectId:
          type: integer
          example: 1

    TaskUpdate:
      type: object
      properties:
        title:
          type: string
        status:
          type: string
          enum: [pendente, concluída]